### PR TITLE
attempt to fix #60

### LINKED ISSUE #60: list not displaying content when filtered by custom attribute
When filtering a list using value converters (not sure if this is the cause, but anyway) the resulting list is essentially empty. The data is still there (`this.items` contains the correct data).
In addition to being "empty" the list is displayed in a different order when removing the filter.

It's reproduced here: https://github.com/Thanood/ui-virt-filter-issue

Steps to reproduce:
- select an item
- scroll down a few pages (to trigger mutations)
- select another item
- enable "show only selected"
- disable "show only selected"

It's interesting that if you scroll to the top before enabling the filter, everything is okay.

### PR DESCRIPTION
**Pull request by Thanood**
This is an attempt to fix #60.
All existing tests succeed, with the exception of two tests which also fail when this change is not added.

Unfortunately, I failed to come up with a new test case for this commit. I could use a little help there. 😃 

Here is what the test should do:
- initialize `virtual-repeat` with `items` being an array of `{ id: i, title: 'item ' + i, isSelected: false }` and an additional viewModel property of `showOnlySelected = false`
- add a `selected` value converter (see below)
- use the value converter like so: `<div virtual-repeat.for="item of items | selected:'isSelected':showOnlySelected">`
- scroll down a few pages
- set `isSelected = true` to two items in the current visible viewport
- set `viewModel.showOnlySelected = true`
- ensure that `virtualRepeat.items` consists of the two items selected previously
- ensure that these items are visible (?) - as in not displayed empty

`selected-value-converter.js`:

```javascript
export class SelectedValueConverter {
  toView(array, selectedProperty, isActive) {
    if (array) {
      if (isActive) {
        return array.filter(item => {
          return !!item[selectedProperty];
        });
      } else {
        return array;
      }
    }
  }
}
```

### CODE REVIEW

**Comment by AStoker** [comment]
Hey @Thanood, has there been any other strangeness with this? It looks like a simple fix (just a different means of getting the index), and it would solve an issue for us on our end. Just want to make sure there wasn't anything missing.

**Comment by Thanood** [comment]
No strangeness apart from me not being able to create a working test case.
Tbh I'm a bit unsure about this. Does this even make sense?

```javascript
return this.view(0) ? this.viewSlot.children.indexOf(this.view(0)) : -1;
```

This will always return `0` right? But in fact it solves my problem in #60.

**Comment by AStoker** [comment]
I'm not entirely sure (I've been a bit out of the repos for a bit due to a busy schedule)...
The getFirstViewIndex function is only called when we're scrolling up and moving views. So we want to know what the index of the first view that we have _currently rendered_ is. DOM wise, this index would always be 0, but if we're scrolling through a large list, the first in the DOM might not be the first in the array. 
So that being said (thinking this through as I type), I'm not sure if this would be appropriate (or would break other things). You're basically asking the view slot what the index of the first view is (which will always be 0, yes). But it appears that the intended behavior is to get the position in the array of the first element in the DOM.

**Comment by AStoker** [comment]
This fix might work for you since in your case, you're wanting to change the array and start back at the top, so getting the "first index" as 0 would do that for you.
But what would happen if the user is just trying to scroll up from a long list? Would it take the user back to the top incorrectly?

**Comment by chuckwatson87-zz** [comment]
Pulled this down and tested for our issue, and was able to confirm @AStoker's theory unfortunately.

**Comment by AStoker** [comment]
@Thanood, would it be appropriate to just say that any time the underlying array count changes, we check our current scrollTop position, and then compare that to the maximum scroll top position, if our current scrollTop position is greater than the max, then set it to be the max. Then recalculate the base heights to fix the scroll bars  
This would give the "trimming" effect when a list gets shorter.

**Comment by Thanood** [comment]
Sorry, this topic easily escapes me somehow and you two have been typing faster. 😃 
Thanks @chuckwatson87 for confirming @AStoker's theory.

> would it be appropriate to just say that any time the underlying array count changes, we check our current scrollTop position, and then compare that to the maximum scroll top position

@AStoker 
In #60 I've logged what happens to the viewSlot children ([here](https://github.com/aurelia/ui-virtualization/issues/60#issuecomment-267934771)) and I guess you're referring to that log, right? The number of children (and thus the calculated first index) seem to be one "step" off.

So yes, I agree. Calculating scrollTop seems like a good idea.
That would be similar to [this proposal](https://github.com/aurelia/ui-virtualization/issues/60#issuecomment-243519715), right?

**Comment by AStoker** [comment]
@Thanood, it does sound like that proposal. I haven't tried this though :) 
I wasn't directly referring to any log, I really need to sit down and read your issue you wrote up and see what's going on. I just haven't had the time yet.

**Comment by Thanood** [comment]
Thanks a lot for reading it. That issue is really bugging me a lot. 😃 
At the moment I'm always applying said proposal after each update to `ui-virtualization`. It works (at least with a list of around 1000 users)..

**Comment by Thanood** [comment]
Closing since there's no point in merging this. 😃

**Pull request closed without merging**
