### PR TITLE
fix(table-virtual-repeat): better handling for repeating table row/body add CI back

### PR DESCRIPTION
**Pull request by bigopon**
a `virtual-repeat` may be used in conjunction with static row, like following:
```html
<table>
  <tr>
    <th>...</th>
  </tr>
  <tr virtual-repeat.for="..."></tr>
  <!-- or -->
  <tbody virtual-repeat.for="...">
    <tr>...</tr>
  </tbody>
</table>
```

So I don't think our current approach of adding buffers outside of table is correct. However, adding buffers inside tables will cause issues with styling, because of extra space between rows / body, when border spacing isn't 0. It's a caveat I think worth mentioning and enforced

Note that previously, we had buffer inside table, however, they came with a `<td/>` in each row, thus messed up table cell styling. Simply adding a `<tr/>` without `<td/>` can help resolve it.

cc @AStoker @martingust @EisenbergEffect @jdanyow @avrahamcool

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bigopon Just to confirm, you don't need review on this yet right?

**Comment by bigopon** [comment]
@EisenbergEffect I've thought about this again, and I think this fix is appropriate.

**Comment by EisenbergEffect** [comment]
Ok, will review soon. Getting later here so might be tomorrow.

**Comment by bigopon** [comment]
@EisenbergEffect There is now an example app at path `sample/sample-v-ui`, which should help testing real app directly against source easier. Do:

```shell
cd sample/sample-v-ui
npm install
npm run dev
```
app at localhost:8080

Edit: an online version of sample app at https://dist-owjyzhcvev.now.sh/#/issue-138

**Comment by EisenbergEffect** [comment]
@bigopon I played with the demo. Oddly, when I scrolled down 700-800 and then started scrolling back up, rendering got weird. It looked like it wasn't rendering the table's bottom half or maybe it was sized wrong or something. Can you try that out and take a look? Please advise on whether you think we should merge this PR (reviewed so ready when you are) and fix this other issue in a new PR or whether you want to work on it as part of this fix. I haven't looked at this code in a long, long time so I'm not sure if it's related to this issue or not.

**Comment by bigopon** [comment]
@EisenbergEffect I've fixed the issue by removing buffer size. Online demo at https://dist-qdzaosxjeb.now.sh/#/issue-138

Though it's pretty puzzling to figure out what exactly causes the glitchy rendering when there is a change in scroll direction, I think this PR is in good state to merge.

**Comment by bigopon** [comment]
> Though it's pretty puzzling to figure out what exactly causes the glitchy rendering 

Also note that the bug only appears when the list is not fixed (i.e there is infinite-scroll-next being employed to get more items)

**Comment by avrahamcool** [comment]
@bigopon 

you have a typo in the documentation part.
you wrote `unline repeate` instead of `unlike repeat`

btw: love the work you done here.

**Comment by bigopon** [comment]
@avrahamcool Thanks

I'm glad you and few others are trying this out, so we have a chance to fix this properly.

**Comment by avrahamcool** [comment]
I'll be happy to try it in my own projects once it's ready.

**Comment by EisenbergEffect** [comment]
Big praise to @bigopon for giving this plugin some much needed love. It's been a while and I'm really glad for this.

**Comment by vermilion** [comment]
@EisenbergEffect can you ship new release so we can test this awaited fix? Thanks in advance

**Comment by EisenbergEffect** [comment]
I'm working on a number of releases over the next few days. This will be part of that batch, so it should be out soon. I'm a bit behind due to catch-up after vacation. Thanks for your patience.

**Pull request merged**
