### PR TITLE
fix(null-repeat-strategy): Correctly handle null / undefined

### PR DESCRIPTION
**Pull request by bigopon**
Fix: #100

### CODE REVIEW

**Review by gheoan — APPROVED** [review]

**Comment by AStoker** [comment]
@bigopon, this looks simple enough :+1: I won't get a chance to look at this until Monday though. Could you do me a favor and add some tests to cover the null case?

**Comment by bigopon** [comment]
Sure I can do it, but wondering if if should also support number repeat strategy ? @AStoker

**Comment by AStoker** [comment]
I would probably separate out those to different commits, @bigopon  👍

**Comment by RichiCoder1** [comment]
*bump*

**Comment by AStoker** [comment]
Once we get some tests in here, and confirm that it works still, I'm fine with this PR.

**Comment by EisenbergEffect** [comment]
@AStoker Can you look at this again?

**Comment by bigopon** [comment]
@AStoker

After some basic analysis for writing test, i realize that the change in this PR is insufficient.

1. Currently the method `instanceChanged` is called too late [[code]](/aurelia/ui-virtualization/blob/master/src/virtual-repeat.js#L162-L179)
2. There are additional jobs being done inside `itemsChanged`

Any ideas how to refactor this @AStoker  ?

**Comment by avrahamcool** [comment]
any news on this?

**Comment by EisenbergEffect** [comment]
@bigopon Do yo have time to take a look at this again and revise the fix?

**Comment by bigopon** [comment]
Im more familiar with virtual repeat now, i should be able to continue this PR. Will update

**Comment by bigopon** [comment]
Latest commit:

* resolve #115 where fix introduced another error
* correctly handle null / undefined with proper calculation reset / re-calculation
* create right buffer for both `ol` & `ul`

**Comment by bigopon** [comment]
@EisenbergEffect @AStoker  It's ready for review

**Comment by bigopon** [comment]
fix gist demo https://gist.run/?id=f12e45770938f3ffa14b713d69cdcb71

**Comment by AStoker** [comment]
@bigopon, can you flatten this PR into a single commit, or at least rename commits to match the format? Once that's done, I'll merge this in.

**Pull request closed without merging**
