### PR TITLE
fix(mutation): properly handle mutation

### LINKED ISSUE #97: ui-virtualization crash on big array changes
Big changes in array cause ui-virtualization crash
```javascript
aurelia-task-queue.js:51 Uncaught TypeError: Cannot read property 'animatableElement' of undefined(…)
getAnimatableElement @ aurelia-templating.js:1507
removeAt @ aurelia-templating.js:1739
removeView @ virtual-repeat.js:605
_removeViewAt @ array-virtual-repeat-strategy.js:213
_runSplices @ array-virtual-repeat-strategy.js:177
_standardProcessInstanceMutated @ array-virtual-repeat-strategy.js:123
instanceMutated @ array-virtual-repeat-strategy.js:104
handleCollectionMutated @ virtual-repeat.js:259
call @ virtual-repeat.js:198
callSubscribers @ aurelia-binding.js:365
call @ aurelia-binding.js:979
flushMicroTaskQueue @ aurelia-task-queue.js:124
(anonymous function) @ aurelia-task-queue.js:68
```

To reproduce make such changes in sample application:
1. In phone-list.html. After "Swap" button add input (line:12)
```html
  <input style="position: fixed" value.bind="value" input.trigger="search()" />
```
2. In phone-list.html. Change source array from "objectArray" to "objectArray3" (line:21) like this: 
```html
  <div virtual-repeat.for="item of objectArray3" class="contact-list-item ${item.name}">
```
3. In phone-list.js. Add implementation of search method, which just replace array content with new items.
```javascript
   
  search () {
    var results = [];

    for (var i= 0; i < this.objectArray.length; i++){
      var item = this.objectArray[i];

      if(item.name.toLowerCase().startsWith(this.value.toLowerCase())) {
        results.push(item);
      }
    }

    this.objectArray3.splice.apply(this.objectArray3, [0, this.objectArray3.length].concat(results));
  }
```
4. In phone-list.js. To the the and of activate method add initial object3Array data
```javascript
   this.objectArray3.splice.apply(this.objectArray3, [0, this.objectArray3.length].concat(results));
```

5. Build, and run application.
In input start typing for first element name. I my case it was "0 Leo Hirthe Sr." so I typed "leo". 
In my case this cause 3 of errors provided earlier.

IN ADDITION if after application load you scroll down and then try type, list will show not existing in source array elements.

NOTE this not happens if you remove items by 1 like in sample application, to reproduce this case you shall add/remove "big" amount of items.

### LINKED ISSUE #133: preserve scroll position after sorting a long list
Hello,

If the user is at the top of a really long list and reverses the list's sorting the current item is now at the bottom. Given that scrolling to the new position is not feasible or even desirable how such a situation should be handled?

### PR DESCRIPTION
**Pull request by bigopon**
At the moment, mutation handling is mimicked from normal repeat, with some extra steps to handle situations virtualization aspect. This works well but there are cases where it fails to handle: scroll position shifting related: list shrinking, list expanding. Beside that, there are cases where a list goes from 0 size without any item height calculated to larger size, and vice versa. I feel that there should be better strategy to handle it:

Instead of trying to react immediately mutation, by removing - both buffer area and real views, and adding new views based on new items, handle mutation in two steps:
- use splice to determine buffer sizes, and total number of views, then update element in DOM with new information
- based on new scroll position, determine new scroll position and recalculate first index of visible views range, then rebind the views.

Also there are cases that are optimizable, which will be properly check by mutation handler.

Thanks to @reinholdk for the logic in test utilities wrt starting location

supersedes & close #101 The logic in this PR is better than original, but still needs 1 more step to handle the scroll position shifting scenario
close #97 I can no longer reproduce the issue with latest commit in this branch
close #133 I dont think there is anything we can do, as typically sort won't change browser scroll position, and it is more of expected behavior than trying to scroll to previously visible item

Demo https://dist-lvkqngigdg.now.sh/#/contrived-examples (IE11 compatible)

cc @EisenbergEffect @AStoker 

----

Unless there is bugs with the demo, it's ready to go anytime.

### CODE REVIEW

**Comment by bigopon** [comment]
@reinholdk thanks for your mutation tests here https://github.com/aurelia/ui-virtualization/pull/149/files#diff-f9c6f75e0cbcb3e402c8dd2e64eae7db

**Comment by reinholdk** [comment]
@bigopon cool, thanks for taking this forward!

**Comment by bigopon** [comment]
@EisenbergEffect Ready to go. Fixed a bug related to value converter integration while adding tests to this scenario. You can check the tests here https://github.com/aurelia/ui-virtualization/pull/149/commits/8332675195f57451533de7994a614b8a664e6298#diff-f9c6f75e0cbcb3e402c8dd2e64eae7db

I'm confident that v-repeat is at good state now, and can be used as a drop-in replacement for normal repeat on array. (For the case where all rows have same height, that is)

**Comment by EisenbergEffect** [comment]
Amazing work @bigopon ! After we get a few more things wrapped, it might be a good time to look at building this out for vNext. You've learned a ton by this experience that I bet will help that go faster.

**Comment by bigopon** [comment]
Yup. Next step would be supporting horizontal scrolling for vCurrent for this first.

**Pull request merged**
