### PR TITLE
fix(repeat): fix `instanceChanged` incorrectly binds views when it's at bottom of the list

### LINKED ISSUE #138: Rough scrolling and broken styles with table
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.3.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
10.13.0

* **NPM Version:**
6.0.1

* **JSPM OR Webpack AND Version**
webpack 4.28.0

* **Browser:**
Chrome 71.x | Firefox 64.x 

* **Language:**
TypeScript 3.2.2

**Current behavior:**
I have tried infinite scrolling with this package.  As user scrolls down, I am adding 30 (chunk size) new items in the array. I have tried this on a normal bootstrap table and a table custom control (also based on bootstrap). In both the cases, I noticed similar problems:

1. The scrolling in Chrome is too rough. The scrollbar as well as the table jumps to often, which results in a jerky scrolling. Sometimes, rows (and columns) expand/collapse automatically (without any explicit/intended user interaction apart from scrolling).
1. Another major problem is that it breaks the style.

To demonstrate the problem I have created a repo: https://github.com/Sayan751/au-virtualization-demo
The repo also has some demo gifs that show the problem: 
* [custom control](https://github.com/Sayan751/au-virtualization-demo/blob/master/problem-demo_custom%20control.gif)
* [table](https://github.com/Sayan751/au-virtualization-demo/blob/master/problem-demo_table.gif)

The screen captures are done on Chrome. The scrolling is somewhat better with Firefox, but it too has the problem with styling.

**Expected/desired behavior:**

* **What is the expected behavior?**
Smooth scrolling is expected that also keeps the styling intact.

* **What is the motivation / use case for changing the behavior?**
Better user experience.

### LINKED ISSUE #146: Rendering issues when scrolled to the bottom and array mutates
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.4

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
9.11.1

* **NPM Version:**
6.8.0

* **JSPM OR Webpack AND Version**
webpack-cli 3.2.3

* **Browser:**
Chrome 72 | IE 11 | Edge 42

* **Language:**
TypeScript 3.1.2

**Current behavior:**
When the table is scrolled right to the bottom and the array is mutated, it renders empty rows after the actual elements. This only happens when it is scrolled right to the bottom.

Sample application demonstrating the bug can be seen here https://github.com/rowellx68/virtual-repeat-sort-issue

render-issue

**Expected/desired behavior:**

* **What is the expected behavior?**
Expected behaviour is for the rows to render correctly and preserving the scroll position when the array mutates.

### PR DESCRIPTION
**Pull request by bigopon**
fixes #146 
fixes #138 

Currently when a new instance is given to virtual repeat, it doesn't account for situation where the index of first view and total existing views count may exceed the number of total items. This fix add a check for that to decrease first index to fit into the right range, also with guard condition to make sure it's 0 minimum.

Demo of fix at https://dist-ecnvjntirz.now.sh/#/issue-146

@EisenbergEffect @AStoker 
@rowellx68

### CODE REVIEW

**Comment by bigopon** [comment]
@rowellx68 In your real code, you don't have `overflow-y: auto` on your `.scroll-container`, making it work correctly, with worse perf because it falls back to listening to scroll event on document and calculates based on document. This is another bug that should be tackled separately.

**Comment by bigopon** [comment]
@EisenbergEffect @AStoker  Now all the following usages are properly handled, buffers are created in more proper position, with right element name:
```html
<ul style="overflow: scroll; height: 500px;">
  <li virtual-repeat.for="item of items">...</li>
</ul>

<div style="overflow: scroll; height: 500px;">
  ... some content
  <ul>
    <li virtual-repeat.for="item of items"></li>
  <ul>
</div>

<table>
  <tbody repeat.for="item of items">...</tbody>
<table>

... with or without container here
<table>
  <tr repeat.for="item of items"></tr>
</table>
```

**Comment by EisenbergEffect** [comment]
Pretty impressive work @bigopon Do we need to make an update to the docs in our documentation repo?

**Comment by bigopon** [comment]
@EisenbergEffect Yes, it should. There is (3) and (4) in caveats section.

**Comment by rowellx68** [comment]
@bigopon @EisenbergEffect Thanks for this. Will give it a go with our codebase.

**Pull request merged**
