### PR TITLE
feat(all): handle home, end, pgup, pgdown keys

### LINKED ISSUE #10: Add support for PageUp, PageDown, Home, and End keys
The plugin supports scrolling by keyboard but does not capture non-arrow keypresses. Quick fix for this is as follows in `scrollHandler.js`:

```
  keyDown(event) {
    var delta = 0;
    switch(event.keyCode) {
      case 36: // Home key
        delta = Number.POSITIVE_INFINITY;
        break;
      case 35: // End key
        delta = Number.NEGATIVE_INFINITY;
        break;
      case 33: // Page up
        delta = this.pageStep;
        break;
      case 34: // Page down
        delta = -this.pageStep;
        break;
      case 38: // Up arrow
        delta = this.keyStep;
        break;
      case 40: // Down arrow
        delta = -this.keyStep;
        break;
    }
```

### PR DESCRIPTION
**Pull request by jwahyoung**
Add additional key event support for better scrolling with the keyboard, mimicking native behavior.

Fixes #10.

### CODE REVIEW

**Comment by jwahyoung** [comment]
Note that the pageDown/pageUp scroll is naive - simply multiplying the keyStep by a static value. It might be better to attempt to use the height of the element somehow to attempt to do a "full-page scroll" instead of just guessing at the ideal keyStep. Perhaps this value could be passed to the scrollHandler initialize function.

**Comment by martingust** [comment]
@jedd-ahyoung Would you mind rebasing just the source file changes with master? And we will build the dist right before making the first release which should be pretty soon.

**Comment by jwahyoung** [comment]
@martingust Should be good now - let me know.

**Comment by jwahyoung** [comment]
@martingust Eh, to clarify - it's good on my fork (and the pull request should be updated accordingly). I don't believe I have push access to the upstream repository. However, if you did want me to rebase my change directly onto the upstream repository, I can do that too. Let me know.

**Pull request merged**
