### PR TITLE
Native scrolling

### PR DESCRIPTION
**Pull request by martingust**
This is an experimental branch on leveraging the browsers native scroll and scroll bar. This pull request should only act as a place to collaborate on the implementation and should not be merged to master. 
#### Approach

The idea for this approach comes from @AStoker

``` css
.scroll-container {
   overflow: scroll;
}
```

``` html
<div class="scroll-container">
   <ul class="scrolling-list">
      <li class="scroll-top-buffer"></li>
      <li virtual-repeat.for="item of items">
        <template replaceable part="item-template"></template>
      </li>
      <li class="scroll-bottom-buffer"></li>
   </ul>
</div>
```

You could then as you scroll through the list of items, determine the height of the element you're popping off and add that height to the `<li class="scroll-top-buffer"></li>`. Likewise for the scroll buffer on the bottom.
#### Implementation

The plugin sets up a `requestAnimationFrame` recursion to check current scroll position. Current scroll position is checked by [looking at `scrollTop`](https://github.com/aurelia/ui-virtualization/blob/native-scrolling/src/virtual-repeat.js#L179) of the container. If the top element is scrolled outside of the view port it gets [moved to the bottom and re-bound](https://github.com/aurelia/ui-virtualization/blob/native-scrolling/src/virtual-repeat.js#L393) to whatever the bindingContext is for that position at the bottom, likewise when scrolling up the elements get scrolled outside of the view port at the bottom, the elements get [moved and re-bound](https://github.com/aurelia/ui-virtualization/blob/native-scrolling/src/virtual-repeat.js#L410) to the top of the list. 

The speed the users scroll will vary a lot, between different devices and scroll inputs. When a user is scrolling faster than what the `requestAnimationFrame` loop can keep up with, list items start being skipped. This is guarded by looking if any elements are skipped and if so, slow down the move/rebind by only taking the [next element in the order](https://github.com/aurelia/ui-virtualization/blob/native-scrolling/src/virtual-repeat.js#L190).  This makes sure that no matter how fast the user scrolls no items will be skipped. However move/rebind-phase only one element has obviously a limit on how many elements can be moved and rebound per time unit. Lets say the list has 1000 items, the user quickly drags the scrollbar to the bottom, the list has to go through move and re-bind almost 1000 items, although only a few items at the bottom will be viewed by the user. To speed up this the lists checks how many items are being skipped, if above a certain threshold ([currently 2 times the number of elements rendered in the DOM](https://github.com/aurelia/ui-virtualization/blob/native-scrolling/src/virtual-repeat.js#L191)) the list skipping move and rebind a certain number of elements ([currently half of the number items being skipped](https://github.com/aurelia/ui-virtualization/blob/native-scrolling/src/virtual-repeat.js#L192)), this gives the list a chance to faster keep up with the scroll position the give the user desired element without have the render unnecessary elements. These numbers can of course be tinkered with. 

In addition to give the list some room to keep up with scrolling a certain number of elements can be buffered above and below. This number should probably be a setting for the user to set depending on requirements.

### CODE REVIEW

**Comment by jdanyow** [comment]
:+1:

**Comment by vamp** [comment]
FYI (another JS-only solution for virtualization): [Clusterize.js](https://github.com/NeXTs/Clusterize.js)

**Comment by martingust** [comment]
@vamp Cool, I like how they split up the list in clusters, that works pretty good. One problem using `Clusterize.js` for is that it will destroy the view comments Aurelia creates to determine the view boundaries. We could use `Clusterize.js` own handling of list changes, however it only support append and prepend also we would loose animation capabilities and the view lifecycle when iterating bahaviors. Perhaps we could look into how they handle the clusters and get some ideas from there. Thanks for the link!

@AStoker thoughts?

**Comment by EisenbergEffect** [comment]
I would prefer not to have any external dependencies. What little 3rd party deps we already have have already caused us ample problems. If we can do this in a self-contained way, we really need to.

**Comment by vamp** [comment]
@EisenbergEffect, clusterize.js provided just only as source for new ideas for implementation :+1: @martingust, inspired by clusterize and created [knockout binding handler for clusterize](https://cloudup.com/cBsdZgzd9iB)

**Comment by AStoker** [comment]
@martingust , I agree with @EisenbergEffect, pulling in more dependencies has been a nightmare for our company using other frameworks. However, it would be nice to look at it for inspiration, yah. 
I've been busy the last few weeks at work, and hopefully things are finally winding down where I can look into this more.

**Comment by EisenbergEffect** [comment]
@martingust I finally had a chance to read your explanation above. Sounds great. Keep moving ahead. I've got a nice use for this very soon :)

**Comment by martingust** [comment]
With the last [commit](https://github.com/aurelia/ui-virtualization/commit/2532d09c4397f725b68a52c8921cb4d0473b9620) I changed the implementation a bit. Move and rebind one view at a time made the list having hard time keep up with fast scrolling, instead [moving views in bulk](https://github.com/aurelia/ui-virtualization/blob/native-scrolling/src/virtual-repeat.js#L252) (like 10 or 20 at a time) makes the update phase much more efficient.

**Comment by EisenbergEffect** [comment]
Nice!

**Comment by martingust** [comment]
Scroll implementation feels pretty solid at this point. Tested with the sample app in Chrome (Mac and Android) and Safari (Mac).

TODO:s before this is ready to be merged:
- ~~Fix bug when quickly switching direction at top or bottom of list.~~
- ~~Fix handling of array mutations (probably just a matter of correctly adjust the buffer heights).~~
- ~~Make work with different view strategies (table, ul etc).~~
- ~~Test on more devices/browsers.~~ 
- ~~Squash commits.~~

Update: So far tested in Chrome, Firefox, Safari on OS X, Chrome on Android, and Safari and Chrome on iOS, works good on all except Chrome on iOS will open issue for that. Also need testing on Microsoft browsers.

**Comment by EisenbergEffect** [comment]
Awesome work @martingust Keep it coming! :clap:

**Comment by jdanyow** [comment]
Awesome! 🚀

**Comment by AStoker** [comment]
I try and avoid just saying "thanks" to threads, but seriously, thanks!

**Pull request merged**
